[package]
edition = "2021"
name = "simtro"
version = "0.1.0"

[dependencies]
ndarray = {version = "0.15", features = ['rayon']}
rand = "0.8"
rand_distr = "0.4"
num-traits = "0.2"
rayon = "1"
splines = "4"